---
title: "Python para Análise de Dados Geográficos"
---

## Visão geral

Esta aula será dividida em três partes:

::: {.incremental}
1. Conceitos básicos de Python
2. Introdução aos dados geográficos com Python
3. Manipulação de dados geográficos com Python
:::

# Conceitos básicos de Python

## Por que usar programação para análise de dados geográficos?

::: {.incremental}
- Automatização de tarefas repetitivas
- Manipulação de grandes volumes de dados
- Reprodutibilidade dos resultados
- Preservação do histórico de operações
:::

## Por que usar Python para análise de dados geográficos?

::: {.incremental}
- Gratuito e de código aberto
- Python é amigável para iniciantes
- Ampla utilização no ecossistema de análise de dados
- Grande interface com ferramentas e bibliotecas de análise de dados geográficos
:::

## Variáveis e tipos de dados

```{python}
#| echo: true
# Exemplo de variáveis e tipos de dados em Python
nome = "João"  # String
idade = 30  # Inteiro
altura = 1.75  # Float
peso = 70.5  # Float
ativo = True  # Booleano
```

## Variáveis e tipos de dados

```{python}
#| echo: true

imc = peso / (altura * altura)  # Cálculo do Índice de Massa Corporal
print(f"O IMC de {nome} é: {imc:.2f}")
```

## Listas

```{python}
#| echo: true
distritos_sp = [
    "Sé",
    "Itaquera",
    "Jaçanã",
    "Moema",
    "Vila Mariana",
]
print(distritos_sp)
```

## Listas - Acessando elementos

```{python}
#| echo: true
print(distritos_sp[0])  # Primeiro elemento
print(distritos_sp[-1])  # Último elemento
```

## Listas - Operações básicas: adicionar
```{python}
#| echo: true
distritos_sp.append("Butantã")  # Adiciona um novo elemento à lista
print(distritos_sp)
```

## Listas - Operações básicas: invertendo a ordem

```{python}
#| echo: true
distritos_sp.reverse() # Inverte a ordem dos elementos na lista
print(distritos_sp)
```

## Listas - Operações básicas: ordenando os elementos
```{python}
#| echo: true
distritos_sp.sort() # Ordena os elementos da lista em ordem alfabética
print(distritos_sp)
```

## Laços - for

```{python}
#| echo: true
# Exemplo ruim
print(distritos_sp[0])
print(distritos_sp[1])
print(distritos_sp[2])
print(distritos_sp[3])
print(distritos_sp[4])
print(distritos_sp[5])
```

## Laços - for

```{.python}
# Exemplo pior
print(distritos_sp[6])
```
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[35], line 2
      1 # Exemplo pior
----> 2 print(distritos_sp[6])

IndexError: list index out of range
```

## Laços - for
```{python}
#| echo: true
# Exemplo bom
for distrito in distritos_sp:
    print(distrito)
```

## Declaração Condicional - if

```{python}
#| echo: true
# Exemplo de declaração condicional
if idade < 18:
    print("Menor de idade")
else:
    print("Maior de idade")
```

## Declaração Condicional - if

```{python}
#| echo: true
# Exemplo de declaração condicional
if idade < 18:
    print("Menor de idade")
elif idade < 65:
    print("Adulto")
else:
    print("Idoso")
```

## Declaração Condicional - if

```{python}
#| echo: true

print(distritos_sp)

for distrito in distritos_sp:
    if "u" in distrito:
        print(f"{distrito} é um distrito que possui a letra 'u'.")
```

## Funções


```{python}
#| echo: true
# Exemplo de função
def calcular_imc(peso, altura):
    imc = peso / (altura * altura)
    return imc

nome_maria = "Maria"
peso_maria = 60.0
altura_maria = 1.65
imc_maria = calcular_imc(peso_maria, altura_maria)
print(f"O IMC de {nome_maria} é: {imc_maria:.2f}")
```

# Análise de dados com Python

## Tabelas

[Wikipedia](https://pt.wikipedia.org/wiki/Lista_dos_distritos_de_S%C3%A3o_Paulo_por_popula%C3%A7%C3%A3o){preview-link="true"}

## Abrindo tabelas com Python

```{python}
#| echo: true
#| code-line-numbers: "|4|7|9|10|"
import pandas as pd

# Lendo a tabela diretamente da Wikipedia
url = "https://pt.wikipedia.org/wiki/Lista_dos_distritos_de_S%C3%A3o_Paulo_por_popula%C3%A7%C3%A3o"

# Configuração de headers para evitar bloqueio por parte do servidor
headers = {"User-Agent": "Chrome/120.0.0.0"}

tabela = pd.read_html(url, header=0, storage_options=headers)[1]
tabela.head(2)  # Exibe as primeiras linhas da tabela
```

## Selecionando linhas

```{python}
#| echo: true
# Selecionando pelo índice
tabela.loc[1]
```

## Selecionando linhas

```{python}
#| echo: true
# Selecionando pela posição
tabela.iloc[1]
```

## Selecionando linhas

```{python}
#| echo: true
# Selecionando pela posição
tabela.iloc[-1]
```

## Selecionando linhas

```{python}
#| echo: true
#| code-line-numbers: "4|"
# Ordena a tabela pelo nome do distrito
tabela.sort_values("Distrito", inplace=True)
tabela.head(4)
```

## Selecionando linhas

```{python}
#| echo: true
# Selecionando pelo índice
tabela.loc[3]
```

## Selecionando linhas

```{python}
#| echo: true
# Selecionando pela posição
tabela.iloc[3]
```

## Selecionando colunas

```{python}
#| echo: true
#| code-line-numbers: "4|"

# Selecionando a coluna de população total
tabela["Pop. Total 2022"].head(4)
```

## Selecionando colunas

```{python}
#| echo: true
# Selecionando a coluna de população total e urbana
colunas = ["Pop. Total 2022", "Pop. Urb. 2022"]
tabela[colunas].head(4)
```

## Calculando estatísticas básicas

```{python}
#| echo: true
# Calculando a média da população total
media_pop_total = tabela["Pop. Total 2022"].mean()
print(f"A média da população total dos distritos é: {media_pop_total:.0f}")
```

## Calculando estatísticas básicas

```{python}
#| echo: true
# Calculando a soma da população total e urbana
colunas = ["Pop. Total 2022", "Pop. Urb. 2022"]
tabela[colunas].sum()
```

## Filtrando dados

```{python}
#| echo: true
# Filtrando os distritos com população total maior que 100.000
filtro = tabela["Pop. Total 2022"] > 100000
tabela[filtro].head(4)
```

## Filtrando dados

```{python}
#| echo: true
# Filtrando os distritos com população total diferente da população urbana
filtro = tabela["Pop. Total 2022"] != tabela["Pop. Urb. 2022"]
tabela[filtro].head(4)
```

## Criando novas colunas

```{python}
#| echo: true
# Criando uma nova coluna de População Rural
tabela["Pop. Rural 2022"] = tabela["Pop. Total 2022"] - tabela["Pop. Urb. 2022"]
tabela.head(4)
```

## Criando novas colunas

```{python}
#| echo: true
tabela.sort_values("Pop. Rural 2022", ascending=False).head(4)
```

## Criando novas colunas

```{python}
#| echo: true
# Criando uma nova coluna de percentual de população rural
tabela["% Pop. Rural 2022"] = 100 * tabela["Pop. Rural 2022"] / tabela["Pop. Total 2022"]
tabela.sort_values("% Pop. Rural 2022", ascending=False).head(4)
```

## Renomeando colunas

```{python}
#| echo: true
tabela.rename(columns={"Unnamed: 0": "Posto"}, inplace=True)
tabela.head(4)
```

## Renomeando colunas

```{python}
#| echo: true
# Criando coluna para os 10 distritos mais populosos
tabela["Posto_numerico"] = tabela["Posto"].str.rstrip(".º").astype(int)
tabela.sort_values("Posto_numerico", inplace=True)
tabela.head(4)
```

## Renomeando colunas

```{python}
#| echo: true
# Criando coluna para os 10 distritos mais populosos
tabela["Dez mais populosos"] = tabela["Posto_numerico"] <= 10
tabela.head(4)
```

## Agrupando e agregando dados

```{python}
#| echo: true
# Agrupando por dez mais populosos e calculando a soma da população total
tabela.groupby("Dez mais populosos")[["Pop. Total 2022"]].sum()
```

## Agrupando e agregando dados

```{python}
#| echo: true
# Agrupando por dez mais populosos e calculando a soma da população total
pop_total = tabela["Pop. Total 2022"].sum()
tabela.groupby("Dez mais populosos")[["Pop. Total 2022"]].sum()/pop_total*100
```

## Juntando tabelas

```{python}
#| echo: true
# Carregando dados de escolas
url_escolas = "https://dados.prefeitura.sp.gov.br/dataset/8da55b0e-b385-4b54-9296-d0000014ddd5/resource/a12ad63d-d944-4e35-9aac-71a5ae0b7bdf/download/escolas122022.csv"
escolas = pd.read_csv(url_escolas, sep=";", encoding="latin1")
escolas.head(4)
```

## Juntando tabelas

```{python}
#| echo: true
escolas[['DISTRITO']].head(4)
```

## Juntando tabelas

```{python}
#| echo: true
escolas_agrupadas = escolas.groupby("DISTRITO").size()
escolas_agrupadas.head(4)
```

## Juntando tabelas

```{python}
#| echo: true
escolas_distrito = escolas_agrupadas.reset_index(name="Número de Escolas")
escolas_distrito.head(4)
```


## Juntando tabelas

```{python}
#| echo: true

# Normalizando os nomes dos distritos para a junção
tabela['DISTRITO'] = tabela['Distrito'].str.upper()
tabela.head(4)
```


## Juntando tabelas

```{python}
#| echo: true
from unidecode import unidecode

# Normalizando os nomes dos distritos para a junção
tabela['DISTRITO'] = tabela['DISTRITO'].apply(unidecode)
tabela.head(4)
```

## Juntando tabelas

```{python}
#| echo: true
# Juntando as tabelas de população e escolas pelo nome do distrito
tabela_juntada = tabela.merge(escolas_distrito, on="DISTRITO", how="left")
tabela_juntada.head(4)
```
